"""esner.is_active

Revision ID: c5e2eccaaf4f
Revises: 
Create Date: 2025-04-30 23:14:20.198182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e2eccaaf4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('esner', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
